name: Shell

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron:  '* 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: sudo wget -O /usr/bin/git-filter-repo https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo
    - run: sudo chmod +x /usr/bin/git-filter-repo

    - run: git remote add upstream $GITHUB_SERVER_URL/Nexus-Mods/extension-theme-switcher.git
    - run: git fetch upstream
    - run: git checkout upstream/$GITHUB_REF_NAME

    - run: git-filter-repo --path-rename themes/compact:themes/compact2 --path-rename themes/contrast:themes/contrast2 --force

    - run: sed 's/^.mainpage-header {/#this-id-does-not-exist {/' -i themes/compact2/style.scss
    - run: sed 's/^.mainpage-header .btn {/#this-id-does-not-exist {/' -i themes/compact2/style.scss
    - run: sed 's/^.mainpage-header {/#this-id-does-not-exist {/' -i themes/contrast2/style.scss
    - run: sed 's/^.mainpage-header .btn {/#this-id-does-not-exist {/' -i themes/contrast2/style.scss
    - run: git show $GITHUB_SHA:.github/style.scss >> themes/compact2/style.scss
    - run: git show $GITHUB_SHA:.github/style.scss >> themes/contrast2/style.scss

    - run: git add .
    - run: git config --global user.email 'galeksandrp@users.noreply.github.com'
    - run: git config --global user.name 'Github CI'
    - run: git commit -m 'Patch'

    - run: git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
    - run: git push origin HEAD:refs/heads/custom-themes -f
